Controllers/AdminController.cs
using expense_classification.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace expense_classification.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public AdminController(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult UnapprovedUsers()
        {
            var users = _userManager.Users.ToList();
            return View(users);
        }

        [HttpPost]
        // Action to toggle user approval status
        public async Task<IActionResult> ToggleApproval(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                user.IsApproved = !user.IsApproved; // Toggle the approval status
                await _userManager.UpdateAsync(user);
            }
            return RedirectToAction("UnapprovedUsers");
        }
    }
}

Controllers/BucketsController.cs
using expense_classification.Data;
using expense_classification.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace expense_classification.Controllers
{
    [Authorize(Roles = "admin")]
    public class BucketsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BucketsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Buckets/List
        public async Task<IActionResult> List()
        {
            var buckets = await _context.Buckets
                                .OrderBy(b => b.Name)  
                                .ToListAsync();

            return View(buckets);
        }

        // GET: Buckets/Add
        public IActionResult Add()
        {
            return View();
        }

        // POST: Buckets/Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(Bucket bucket)
        {
            if (ModelState.IsValid)
            {
                _context.Buckets.Add(bucket);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(List));
            }
            return View(bucket);
        }

        // GET: Buckets/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var bucket = await _context.Buckets.FindAsync(id);
            if (bucket == null)
            {
                return NotFound();
            }
            return View(bucket);
        }

        // POST: Buckets/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Bucket bucket)
        {
            if (id != bucket.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Update(bucket);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(List));
            }
            return View(bucket);
        }

        // POST: Buckets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bucket = await _context.Buckets.FindAsync(id);
            _context.Buckets.Remove(bucket);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(List));
        }
    }
}

Controllers/TransactionsController.cs
using expense_classification.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

using CsvHelper;
using Microsoft.AspNetCore.Hosting;
using NuGet.Protocol.Core.Types;
using System.Globalization;
using CsvHelper.Configuration;
using expense_classification.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace expense_classification.Controllers
{
    [Authorize]
    public class TransactionsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _environment;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<TransactionsController> _logger;

        public TransactionsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IWebHostEnvironment environment, ILogger<TransactionsController> logger)
        {
            _context = context;
            _userManager = userManager;
            _environment = environment;
            _logger = logger;
        }

        // GET: Transactions/Upload
        public IActionResult Upload()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetVendorsByBucket(string bucketName)
        {
            // Fetch the list of vendors for the selected bucket
            var vendors = await _context.Buckets
                                        .Where(b => b.Name == bucketName)
                                        .Select(b => b.Vendor)
                                        .Distinct()
                                        .ToListAsync();

            // Return the list of vendors as JSON
            return Json(vendors);
        }

        // POST: Transactions/Upload
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upload(IFormFile file)
        {
            if (file == null || file.Length == 0)
            {
                ModelState.AddModelError("", "Please select a file to upload.");
                return View();
            }

            try
            {
                var user = await _userManager.GetUserAsync(User);
                if (user == null)
                {
                    ModelState.AddModelError("", "User not found.");
                    return View();
                }

                _logger.LogInformation("User {UserId} is uploading a file.", user.Id);

                // Define the path to save the file
                var uploadsFolder = Path.Combine(_environment.ContentRootPath, "Uploads", user.Id);
                if (!Directory.Exists(uploadsFolder))
                {
                    Directory.CreateDirectory(uploadsFolder);
                }

                // Get the original file name
                var originalFileName = Path.GetFileName(file.FileName);

                // Define the file path
                var filePath = Path.Combine(uploadsFolder, originalFileName);

                // Save the uploaded file
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                }

                // Rename the file by adding '.imported' extension
                var importedFilePath = filePath + ".imported";
                System.IO.File.Move(filePath, importedFilePath);

                // Process the renamed file
                var config = new CsvConfiguration(CultureInfo.InvariantCulture)
                {
                    HasHeaderRecord = false,
                    MissingFieldFound = null,
                    BadDataFound = null,
                    IgnoreBlankLines = true
                };

                using (var reader = new StreamReader(importedFilePath))
                using (var csv = new CsvReader(reader, config))
                {
                    csv.Context.RegisterClassMap<TransactionMap>();
                    var records = csv.GetRecords<Transaction>();

                    foreach (var transaction in records)
                    {
                        _logger.LogInformation("Adding transaction: {Vendor}, {Amount}, {Date}", transaction.Vendor, transaction.Amount, transaction.Date);

                        // Set the UserId for the transaction
                        transaction.UserId = user.Id;

                        // Check if the Bucket already exists
                        var existingBucket = await _context.Buckets
                                                        .FirstOrDefaultAsync(b => b.Name == transaction.BucketName && b.Vendor == transaction.Vendor);
                        
                        // If the bucket doesn't exist, add a new entry to the Bucket table
                        if (existingBucket == null)
                        {
                            var newBucket = new Bucket
                            {
                                Name = transaction.BucketName,
                                Vendor = transaction.Vendor
                            };
                            _context.Buckets.Add(newBucket);
                        }

                        // Add the transaction to the Transactions table
                        _context.Transactions.Add(transaction);
                    }
                    await _context.SaveChangesAsync();
                    _logger.LogInformation("Transactions and Buckets saved to the database.");
                }

                TempData["SuccessMessage"] = "Transactions uploaded successfully.";
                return RedirectToAction("Upload");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An error occurred while processing the file.");
                ModelState.AddModelError("", $"An error occurred while processing the file: {ex.Message}");
                return View();
            }
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAllTransactions()
        {
            try
            {
                _logger.LogInformation("Admin is deleting all transactions.");

                // Delete all transactions
                _context.Transactions.RemoveRange(_context.Transactions);
                await _context.SaveChangesAsync();

                TempData["SuccessMessage"] = "All transactions have been deleted.";
                return RedirectToAction(nameof(Upload));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An error occurred while deleting transactions.");
                TempData["ErrorMessage"] = "An error occurred while deleting transactions.";
                return RedirectToAction(nameof(Upload));
            }
        }

        public sealed class TransactionMap : ClassMap<Transaction>
        {
            public TransactionMap()
            {
                Map(m => m.Date)
                    .Index(0)
                    .TypeConverterOption.Format("MM/dd/yyyy");
                Map(m => m.Vendor)
                    .Index(1);
                Map(m => m.BucketName)
                    .Index(2);
                Map(m => m.Amount)
                    .Index(3)
                    .TypeConverterOption.CultureInfo(CultureInfo.InvariantCulture);
                Map(m => m.Balance)
                    .Index(4)
                    .TypeConverterOption.CultureInfo(CultureInfo.InvariantCulture);
            }
        }

        //List transaction
        [HttpGet]
        public async Task<IActionResult> List()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Unauthorized();
            }

            // Fetch transactions for the logged-in user
            var transactions = await _context.Transactions
                                            .Where(t => t.UserId == user.Id)
                                            .ToListAsync();

            return View(transactions);  
        }

        //Edit transaction
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            var transaction = await _context.Transactions
                                            .FirstOrDefaultAsync(t => t.Id == id && t.UserId == user.Id);

            if (user == null) 
            {
                return Unauthorized();
            }
            if (transaction == null)
            {
                return NotFound();
            }


            // Fetch unique bucket names from the database
            var uniqueBuckets = await _context.Buckets
                                            .Select(b => b.Name)
                                            .Distinct()
                                            .ToListAsync();

            // Populate the ViewBag with the unique bucket names
            ViewBag.BucketList = uniqueBuckets.Select(b => new SelectListItem
            {
                Value = b,
                Text = b
            }).ToList();

            // Populate the VendorList based on the selected bucket
            var vendors = await _context.Buckets
                                        .Where(b => b.Name == transaction.BucketName)
                                        .Select(b => b.Vendor)
                                        .Distinct()
                                        .ToListAsync();

            ViewBag.VendorList = vendors.Select(v => new SelectListItem
            {
                Value = v,
                Text = v
            }).ToList();

            return View(transaction);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

Views/Shared/UnapprovedUsers.cshtml
@model IEnumerable<ApplicationUser>

<h2>Unapproved Users</h2>

<table class="table">
    <thead>
        <tr>
            <th>Email</th>
            <th>Approve</th>
        </tr>
    </thead>
    <tbody>
    @foreach (var user in Model)
    {
        <tr>
            <td>@user.Email</td>
            <td>
                <form asp-action="ApproveUser" method="post">
                    <input type="hidden" name="id" value="@user.Id" />
                    <button type="submit" class="btn btn-success">Approve</button>
                </form>
            </td>
        </tr>
    }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - expense_classification</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/expense_classification.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @if (User.Identity.IsAuthenticated)
        {
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Expense Manager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transactions" asp-action="Upload">Upload</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Transactions" asp-action="List">Transaction</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reports" asp-action="Reports">Report</a>
                        </li>
                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Buckets" asp-action="List" style="color:blue !important">Buckets</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Admin" asp-action="UnapprovedUsers" style="color:blue !important">User Management</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
        }
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 Expense Manager by Juan Chung(A01353601), Ran Park(A01331544) <a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>